// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var chart;
    return chart = new Highcharts.Chart({
      chart: {
        renderTo: 'iteration-chart-container'
      },
      title: {
        text: 'Aufwand pro Iteration'
      },
      xAxis: {
        categories: ['Iteration 1', 'Iteration 2', 'Iteration 3', 'Iteration 4'],
        tickColor: ''
      },
      yAxis: [
        {
          labels: {
            style: {
              font: '13px "Open Sans"'
            }
          },
          title: {
            text: "Stunden",
            style: {
              fontWeight: 'bold',
              fontSize: '18px',
              fontFamily: 'Open Sans'
            }
          }
        }, {
          labels: {
            style: {
              font: '13px "Open Sans"',
              color: "#ED561B"
            }
          },
          title: {
            text: "Velocity",
            style: {
              fontWeight: 'bold',
              fontSize: '18px',
              fontFamily: 'Open Sans',
              color: "#ED561B"
            }
          },
          opposite: true,
          min: 0,
          max: 4
        }
      ],
      tooltip: {
        formatter: function() {
          var s;
          if (this.point.name) {
            return s = "" + this.point.name + ": " + this.y + " fruits";
          } else {
            return s = "" + this.x + ": " + this.y;
          }
        }
      },
      series: [
        {
          type: 'column',
          name: 'Geschätzte Zeit',
          data: [0, 58, 42, 58]
        }, {
          type: 'column',
          name: 'Tatsächliche Zeit',
          data: [96, 63.81, 39.75]
        }, {
          name: 'Velocity',
          yAxis: 1,
          data: [3.43, 2.2, 1.89]
        }, {
          color: "#ED561B",
          dashStyle: "Dash",
          yAxis: 1,
          data: [1.89, 2],
          showInLegend: false,
          pointStart: 2
        }
      ]
    });
  });

}).call(this);
